version: '3.1'

services:

  #
  # https://hub.docker.com/_/mongo
  #
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  #
  # https://www.npmjs.com/package/mongo-express
  #
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081  
    environment:  
      ME_CONFIG_BASICAUTH_USERNAME: 'admin'
      ME_CONFIG_BASICAUTH_PASSWORD: 'admin'
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      #VCAP_APP_HOST: 'localhost'
      #VCAP_APP_PORT: '8081'
      ME_CONFIG_MONGODB_URL: 'mongodb://admin:admin@mongo:27017/db?ssl=false'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'admin'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'admin'
      #ME_CONFIG_MONGODB_AUTH_DATABASE
      #ME_CONFIG_MONGODB_AUTH_USERNAME
      #ME_CONFIG_MONGODB_AUTH_PASSWORD
      #ME_CONFIG_SITE_BASEURL: '/'
      #ME_CONFIG_SITE_COOKIESECRET: 'cookiesecret'
      #ME_CONFIG_SITE_SESSIONSECRET: 'sessionsecret'
      #ME_CONFIG_OPTIONS_READONLY: 'false'
      #ME_CONFIG_OPTIONS_NO_DELETE: 'false'
